### ISSUE TITLE
Where is neutralitytestr!

### ISSUE THREAD

**Issue by caravagn** [marcjwilliams1/neutralitytestr#3]
```
> out <- neutralitytest(VAFneutral, fmin = 0.1, fmax = 0.25)
This package has been superseded by MOBSTER, see Caravagna et al. Nature Genetics 2020.
```

Marc! I need to run this :( 

Is there any param to avoid that message! I feel guilty.

**Comment by caravagn** [comment]
Ohhhh but it is just a message, I got my `out` back! 

Sorry, I'll close this :)

**Comment by marcjwilliams1** [comment]
Yeah, I just thought a message would be good in order to alert people to what the latest and greatest neutral tumour evolution analysis is. I think people should be using MOBSTER in general rather than what we did in 2016. What do you think? OK having that message there?

**Comment by caravagn** [comment]
Ah no it's fine!  It's just that when I have seen the red message I thought I could not use it, which was not the case. So I opened the issue but then realized and closed that! Sorry eheh :) this is still handy sometimes!
